apiVersion: v1
kind: Config
preferences: {}
clusters:
  - name: arn:aws:eks:us-east-1:111111111111:cluster/example-cluster
    cluster:
      server: https://EXAMPLE.gr7.us-east-1.eks.amazonaws.com
      certificate-authority-data: <BASE64_CA_DATA>
contexts:
  - name: dev
    context:
      cluster: arn:aws:eks:us-east-1:111111111111:cluster/example-cluster
      user: arn:aws:eks:us-east-1:111111111111:cluster/example-cluster
current-context: dev
users:
  - name: arn:aws:eks:us-east-1:111111111111:cluster/example-cluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws
        args:
          - --region
          - us-east-1
          - eks
          - get-token
          - --cluster-name
          - example-cluster
          - --output
          - json
        env:
          - name: AWS_PROFILE
            value: dev
        interactiveMode: IfAvailable
        provideClusterInfo: false
